Allowing session cookie (split cookie)
lexik/LexikJWTAuthenticationBundle pull request #958
Opened 2021-11-22 12:55 UTC by JeremyPasco

AS described in #809, the split cookie approach cannot be fully implemented because this bundle doesn't allow session cookie (when lifetime=0, then the token ttl value was used instead). This pull request allows a 0 lifetime cookie:

lexik_jwt_authentication.yaml
```
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 86400
    token_extractors:
        split_cookie:
            enabled: true
            cookies:
                - jwt_hp
                - jwt_s
    set_cookies:
        jwt_hp:
            lifetime: 360
            samesite: strict
            path: /
            domain: null
            httpOnly: false
            split:
                - header
                - payload

        jwt_s:
            lifetime: 0 # session cookie here
            samesite: strict
            path: /
            domain: null
            httpOnly: true
            split:
                - signature
```

2021-11-22 12:57 UTC, chalasr commented
Thanks a lot for the PR! Could you please add a test case?

2021-11-23 13:37 UTC, JeremyPasco commented
Done :)
I also updated the documentation for split_cookie to reflect the idea behind [this article](https://medium.com/lightrail/getting-token-authentication-right-in-a-stateless-single-page-application-57d0c6474e3): the signature cookie should be a session one.

2021-12-05 17:28 UTC, chalasr commented
Sorry for not reviewing this earlier, my open-source time was quite limited these 2 last weeks.
I'm going to have a deep look at this as soon as possible.

2021-12-08 17:58 UTC, chalasr requested changes

2021-12-08 17:58 UTC, chalasr commented on Security/Http/Cookie/JWTCookieProvider.php
> +            $expiresAt = $this->defaultLifetime == 0 ? 0 : (time() + $this->defaultLifetime);
```suggestion
            $expiresAt = 0 === $this->defaultLifetime ? 0 : (time() + $this->defaultLifetime);
```

2021-12-08 17:58 UTC, chalasr commented on Tests/Security/Http/Cookie/JWTCookieProviderTest.php
> +}
Missing EOF
```suggestion

}
```

2021-12-08 18:04 UTC, merged

2021-12-08 18:06 UTC, chalasr commented
I kinda missed up with git while merging, but everything is ok. Thank you very much @JeremyPasco.