Translate message errors
lexik/LexikJWTAuthenticationBundle pull request #973
Opened 2021-12-29 14:16 UTC by flohw

Hi @chalasr,

The exception messages are not translated even if the locale was set.
I largely ~copied~ inspired my code from this PR: symfony/symfony#38037 to translate the message.

Let me know if any changes need to be done.

2021-12-29 14:18 UTC, flohw commented
I just noted that on the original PR translations are made in the authenticator. It may be a better choice as the listener can be changed by the developer.

Let me know if I missed something and should update to translate in the authenticators too or only in them.

Thank you

2021-12-29 14:24 UTC, chalasr requested changes
Thanks a lot for the PR. Here are some suggestions :)

2021-12-29 14:24 UTC, chalasr commented on Security/Http/Authentication/AuthenticationFailureHandler.php
>      public function __construct(EventDispatcherInterface $dispatcher)
Let's use a nullable constructor parameter instead of the setter

2021-12-29 14:24 UTC, chalasr commented on Security/Http/Authentication/AuthenticationFailureHandler.php
> +    protected $translator;
please make it `private` (yes that's inconsistent but we don't want to provide such extension points anymore)

2021-12-29 14:26 UTC, chalasr commented
Don't worry about the failing tests, it's unrelated. I need to look into them, sorry about that.

2021-12-29 14:44 UTC, flohw commented
Thank you for this quick review! I updated the code accordingly. (sorry for the multiple push force, I struggled with my gpg key...)

Also note about this comment above:
> I just noted that on the original PR translations are made in the authenticator. It may be a better choice as the listener can be changed by the developer.
> 
> Let me know if I missed something and should update to translate in the authenticators too or only in them.

Should I update the other place where `strtr` is used?

2021-12-29 17:42 UTC, chalasr approved these changes

2021-12-29 17:46 UTC, chalasr commented
Sorry I was unsure to understand your question, got it now.
If you could do the same in the jwt authenticator that would be awesome (both are good, so what you already did is valid!)

2021-12-30 08:16 UTC, flohw commented
Hi @chalasr,

Thanks I just added translator in both authenticators (JWT and JWTToken).

2021-12-31 15:07 UTC, chalasr approved these changes

2022-01-05 08:16 UTC, flohw commented
Hi @chalasr 
I just saw the new release and rebase my branch.
The failing tests have changed. I am not sure if it's on my side to repair especially for the PHP8/SF5.3 couple.

Thanks

2022-01-05 13:58 UTC, chalasr commented
No worries, it's due to a Symfony bug revealed by your changes. See https://github.com/symfony/symfony/pull/44918 for the fix.

2022-01-27 10:26 UTC, chalasr commented
Thanks @flohw for working on this feature, this is much appreciated.

2022-01-27 10:26 UTC, merged