Add Request object into AuthenticationFailureEvent
lexik/LexikJWTAuthenticationBundle pull request #995
Opened 2022-03-16 09:44 UTC by Dumra

Want to get Request object in the subscriber for AuthenticationFailureEvents for passing some data regarding the occurred exception to e.g. `symfony:terminate` event subscriber .

2022-03-16 17:43 UTC, chalasr requested changes
Hey, thanks for the PR! Here are some comments

2022-03-16 17:43 UTC, chalasr commented on Event/AuthenticationFailureEvent.php
> +    protected $request;
```suggestion
    private $request;
```

2022-03-16 17:43 UTC, chalasr commented on Event/AuthenticationFailureEvent.php
> +    public function __construct(AuthenticationException $exception, Response $response, Request $request)
```suggestion
    public function __construct(AuthenticationException $exception, Response $response, ?Request $request = null)
```

BC break otherwise :)

2022-03-16 17:43 UTC, chalasr commented on Event/AuthenticationFailureEvent.php
> +    public function getRequest() {
```suggestion
    public function getRequest(): ?Request
    {
```

2022-03-16 17:43 UTC, chalasr commented on Event/AuthenticationFailureEvent.php
> +     * @var Request
```suggestion
     * @var Request|null
```

2022-03-16 17:43 UTC, chalasr commented on Event/AuthenticationFailureEvent.php
> +    public function setRequest(Request $request) {
```suggestion
    public function setRequest(Request $request): void
    {
```

2022-03-16 17:43 UTC, chalasr commented on Event/AuthenticationFailureEvent.php
> +use Symfony\Component\HttpFoundation\{Request, Response};
```suggestion
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
```

2022-03-16 17:49 UTC, Dumra commented on Event/AuthenticationFailureEvent.php
> +    protected $request;
updated

2022-03-16 17:49 UTC, Dumra commented on Event/AuthenticationFailureEvent.php
> +    public function __construct(AuthenticationException $exception, Response $response, Request $request)
updated

2022-03-16 17:49 UTC, Dumra commented on Event/AuthenticationFailureEvent.php
> +    public function getRequest() {
updated

2022-03-16 17:49 UTC, Dumra commented on Event/AuthenticationFailureEvent.php
> +     * @var Request
updated

2022-03-16 17:49 UTC, Dumra commented on Event/AuthenticationFailureEvent.php
> +    public function setRequest(Request $request) {
updated

2022-03-16 17:49 UTC, Dumra commented on Event/AuthenticationFailureEvent.php
> +use Symfony\Component\HttpFoundation\{Request, Response};
updated

2022-03-16 18:28 UTC, chalasr approved these changes
Looks good!

2022-03-16 18:32 UTC, chalasr commented
Thank you @Dumra.

2022-03-16 18:32 UTC, merged

2022-03-16 18:36 UTC, chalasr commented
This should be released in a week or so (I just have a change of mine to finish beforehand). Feel free to require 2.x-dev meanwhile, and take care of yourself :) #StandWithUkraine

2022-03-16 18:40 UTC, Dumra commented
Sounds great!
Thank you for u support!

2022-03-25 16:56 UTC, Dumra commented
Hey, @chalasr . 
When're u go' to create a new release?